### ISSUE TITLE
undefined method `dirty?' for Barista::Compiler:Class exception

### ISSUE THREAD

**Issue by nicolasblanco** [Sutto/barista#10]
Hi!

Compiler does not have the "dirty?" method ?!

<pre>
ree-1.8.7-2010.02 > [$]nicolas@nicolas-desktop:[git:master] /home/nicolas/projects/novagolf-> rails c
Loading development environment (Rails 3.0.1)
ree-1.8.7-2010.02 > Barista::Compilers::Node.available?
true
ree-1.8.7-2010.02 > Barista.compile_all!
NoMethodError: undefined method `dirty?' for Barista::Compiler:Class
    from /home/nicolas/.rvm/gems/ree-1.8.7-2010.02@novagolf/gems/barista-0.6.0/lib/barista.rb:94:in `compile_file!'
    from /home/nicolas/.rvm/gems/ree-1.8.7-2010.02@novagolf/gems/barista-0.6.0/lib/barista.rb:115:in `compile_all!'
    from /home/nicolas/.rvm/gems/ree-1.8.7-2010.02@novagolf/gems/barista-0.6.0/lib/barista.rb:114:in `each'
    from /home/nicolas/.rvm/gems/ree-1.8.7-2010.02@novagolf/gems/barista-0.6.0/lib/barista.rb:114:in `compile_all!'
    from (irb):2
</pre>

**Comment by nicolasblanco** [comment]
Workaround..? :

https://github.com/Sutto/barista/pull/11

**Comment by shaug** [comment]
I monkeypatched this in my `barista.rb` initializer:

```
module Barista
  class Compiler
    def self.dirty?(*args)
      compiler_klass.dirty?(*args)
    end
  end
end
```

**Comment by nicolasblanco** [comment]
merged. thanks.
