### ISSUE TITLE
Running rake barista:brew (Node Compiler) using Capistrano always fail

### ISSUE THREAD

**Issue by nicolasblanco** [Sutto/barista#13]
hi,

Running rake barista:brew (Node Compiler) using Capistrano always fail with :
"... exited with a non-zero status.".

My cap recipe is just like this :

<pre>
run "cd #{release_path} && rake RAILS_ENV=#{rails_env} barista:brew"
</pre>

When I run rake barista:brew directly on my prod box with a shell it works.
So I think that it's the way Barista launches the coffee executable that does not work when it is launched by Capistrano...

Thanks,

Nicolas.

**Comment by Sutto** [comment]
It sounds like it's likely an issue with CoffeeScript not being in the path. Where do you have coffeescript installed (via npm) and also try running the command via ssh - namely, ssh user@host 'which coffee' - that should return a path.

**Comment by Sutto** [comment]
I'm closing this as it's related to another ticket. See #12
