### ISSUE TITLE
haml filter load issue

### ISSUE THREAD

**Issue by hynkle** [Sutto/barista#19]
I'm not quite sure why my app happens to behave this way (presumably others' don't, since no one else has mentioned this problem), but I get an "uninitialized constant Haml::Filters" NameError when trying to start my app after installing Barista.  The Barista code this is coming from is in lib/barista/haml_filter.rb:
    def self.setup
      if defined?(Haml)
        CoffeeScript.module_eval { include Haml::Filters::Base }
      end
    end

At this point in my app's load process, Haml is indeed defined, but Haml::Filters is not.  I can fix the problem by adding "require haml/filters" before the `module_eval`, but not being particularly familiar with the conventions of using `require` in gems, I don't know if this is a good idea.  Perhaps `require 'haml/filters' unless defined?(Haml::Filters)`?

I'm using Haml 3.0.25 (currently the most recent) and Rails 3.0.3 (also currently the most recent).

**Comment by Sutto** [comment]
Hi hynkle,

I'm not sure what's causing the issues - just requiring 'haml' (3.0.25) in irb defines Haml::Filters for me. I've released 1.0 either way that requires haml/filters which should hopefully fix the issue - Could you please try and see if that fixes it for you?

Cheers

**Comment by Sutto** [comment]
I'm closing this as I haven't heard any more on this.
