### ISSUE TITLE
Barista::Compiler depends on Object#present? (part of ActiveSupport)

### ISSUE THREAD

**Issue by Burgestrand** [Sutto/barista#20]
https://github.com/Sutto/barista/blob/master/lib/barista/compiler.rb#L26

CoffeeScript.engine will [either be nil or an engine](https://github.com/josh/ruby-coffee-script/blob/master/lib/coffee_script.rb#L178). The actual CoffeeScript#engine would have to have returned `true` for #supported? to not be nil. Therefore, this should be sufficient: `not CoffeeScript.engine.nil?`

**Comment by Sutto** [comment]
Ah, cheers for picking this up - I've changed that line of code (and another instance of present?) and I'll push them in the next release.
