### ISSUE TITLE
Fails to compile files with non-ASCII characters under Ruby 1.9

### ISSUE THREAD

**Issue by javierv** [Sutto/barista#22]
Running barista:brew under Ruby 1.9.2 failed with the following backtrace

```
** Invoke barista:brew (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute barista:brew
rake aborted!
"\xC3" from ASCII-8BIT to UTF-8
.gems/gems/barista-1.0.0/lib/barista/compiler.rb:123:in `write'
.gems/gems/barista-1.0.0/lib/barista/compiler.rb:123:in `block in save'
.gems/gems/barista-1.0.0/lib/barista/compiler.rb:123:in `open'
.gems/gems/barista-1.0.0/lib/barista/compiler.rb:123:in `save'
.gems/gems/barista-1.0.0/lib/barista/compiler.rb:55:in `autocompile_file'
.gems/gems/barista-1.0.0/lib/barista.rb:178:in `block in compile_all!'
.gems/gems/barista-1.0.0/lib/barista.rb:177:in `each'
.gems/gems/barista-1.0.0/lib/barista.rb:177:in `compile_all!'
.gems/gems/barista-1.0.0/lib/barista/tasks/barista.rake:9:in `block (2 levels) in <top (required)>'
```

After removing some spanish accented characters from my CoffeeScript files, it worked fine, so I guess it might have something to do with Ruby 1.9 and encoding (works fine under Ruby 1.8).

I don't know if it's relevant, but I'm using therubyracer.

Not sure if it's a bug or I just have to do something I haven't found in the documentation.

Thanks.

**Comment by nicholaides** [comment]
+1 on this. I'm using Ruby 1.9 with rubyracer, too.

**Comment by javierv** [comment]
After some investigation, it seems that it probably isn't a barista issue. I've reported to the CoffeeScript gem:

https://github.com/josh/ruby-coffee-script/issues#issue/6

According to them, it seems to be a ruby racer issue.

**Comment by nicholaides** [comment]
Thanks for looking into this.

**Comment by Sutto** [comment]
Cheers javierv - I'll close this issue for the moment then.
