### ISSUE TITLE
Way of using compiled js

### ISSUE THREAD

**Issue by elcuervo** [Sutto/barista#25]
Hello i was trying to use :javascript in haml but does not seems to compile coffeescript in rails 3.0.3.
Is there any other way instead of requiring coffee-script.js and using the :coffeescript filter in haml?

**Comment by Sutto** [comment]
Hey elcuervo, if you set Barista.embedded_interpreter to true and use the bundled coffee script filter, it will automatically compile them when it embeds them versus embedding raw coffeescript. (so, you still need to use the coffeescript filter, you just need to use an option to tell barista to compile it versus embedding the coffeescript interpreter in your page)

**Comment by Sutto** [comment]
I'm closing this since there has been no further comments.

**Comment by elcuervo** [comment]
Oops, sorry about this issue, i totally forgot about it. You helped me with that, so yes, is closed :D
