### ISSUE TITLE
Set output_root for frameworks

### ISSUE THREAD

**Issue by bgarret** [Sutto/barista#27]
Is there a mean to set output_root for a framework? This would be very useful when developing rails 3.1 engines, especially the ones with an isolated namespace. I noticed the option in the code but there doesn't seem to be a way to set it without patching barista.

Would it be possible to add this as an option to Barista::Framework.register or add an attribute writer to the Framework class?

**Comment by Sutto** [comment]
Not currently - I'm currently adding it to barista and will let you know once there is support.

**Comment by Sutto** [comment]
Take a look now - you should be able to register frameworks with the option (see the generatable initializer) or use Barista.change_output_root! framework_name, new_root

**Comment by Sutto** [comment]
Not that this is only on master.

**Comment by bgarret** [comment]
Yay, thanks a lot. I'm not using coffeescript anymore (interfacing with Sencha is weird), but it was a pain point when creating rails engine distributed as gems.
