### ISSUE TITLE
RSpec NameError: uninitialized constant CoffeeScript::Engines

### ISSUE THREAD

**Issue by dre3k** [Sutto/barista#31]
Hi, Darcy

I have very simple rails app:
    # Gemfile
    source 'http://rubygems.org'
    gem 'rails', '3.0.5'
    gem 'sqlite3'
    gem 'therubyracer', :require => false
    gem 'barista'
    gem 'rspec'
    gem 'rspec-rails'
    gem 'webrat'
    gem 'capybara'

Set up for rspec-rails and barista:
    $ rails generate rspec:install
    $ rails generate barista:install

Generate User scaffold and migrate db:
    $ rails generate scaffold user name:string
    $ rake db:migrate

I have app/coffeescripts/application.coffee with just one line:
    # app/coffeescripts/application.coffee
    echo "hello"

When I'm trying to run
    $ rspec spec/requests/users_spec.rb
I get `NameError: uninitialized constant CoffeeScript::Engines`
    F

```
Failures:

  1) Users GET /users works! (now write some real specs)
     Failure/Error: get users_path
     NameError:
       uninitialized constant CoffeeScript::Engines
     # <internal:prelude>:10:in `synchronize'
     # ./spec/requests/users_spec.rb:7:in `block (3 levels) in <top (required)>'

Finished in 0.31144 seconds
1 example, 1 failure
```

Could you please suggest what to do to make rpsec work with barista.

Appreciate your help.

**Comment by dre3k** [comment]
A lot of apologies. It's totally my fault.
I was playing around with barista specifications, and manually changed coffee-script dependency to version to 2.2.0.

**Comment by Sutto** [comment]
Heh, no problem - I'll work shortly on updating barista to work with the newest version given it supports a lot more engines.
