### ISSUE TITLE
forcing coffee-script 2.1.x?

### ISSUE THREAD

**Issue by jacquescrocker** [Sutto/barista#34]
coffee-script 2.2.0 is out and it looks like there isn't any major compatibility issues

barista won't let me upgrade because it depends on 2.1.3. Mind changing the ruby dependency to use `>=` instead of `~>`

thanks

**Comment by Sutto** [comment]
Apologies about the delay in getting to this. I kept the dependency as ~> but changes it to 2.1 so it should work up intil 3.0; This will be pushed out in the next release of the gem as well.

**Comment by Sutto** [comment]
Closing since I haven't heard back from you.
