### ISSUE TITLE
Forcing Sinatra middleware

### ISSUE THREAD

**Issue by jacquescrocker** [Sutto/barista#35]
Currently using Barista in a Sinatra app, purely as a rake task

However as soon as I add it to my Gemfile, Barista instantly adds its middleware onto `Sinatra::Base`. My initializer has to then remove the middleware entries. 

According to Sinatra Extension [docs](http://www.sinatrarb.com/extensions.html), the best practice for this sort of thing is to require the user to opt into middleware. So I would register my middleware manually (or all at once in an initializer). I believe auto wiring up middleware on load is a problem.

I'd highly recommend adding a def self.registered call to the base module of Barista so I can just do a `register Barista` anywhere in sinatra and have it wire up the middleware then.

**Comment by Sutto** [comment]
I think the only thing I dislike about using `register Barista` is that it will extend the app using the barista class.

I've removed the auto-registration aspect (as that was a bad idea) but for the moment I've made it so you `register Barista::Integration::Sinatra`.

**Comment by jacquescrocker** [comment]
Works for me. Thanks!
