### ISSUE TITLE
allow subdirs in input root

### ISSUE THREAD

**Issue by sunaku** [Sutto/barista#41]
Hello,

I would like Barista to compile `app/coffeescripts/foo/bar/baz.coffee` into `public/javascripts/foo/bar/baz.js`.

Thanks for your consideration.

**Comment by Sutto** [comment]
As far as I know, this should already work?

**Comment by sunaku** [comment]
Ah, you're right, sorry for the noise.

I am using Barista 1.0.0 and when I initially accessed `/javascripts/foo/bar/baz.js` in my Rails app, I got a RouteError regarding `/foo/bar/baz.coffee`.  I stopped and restarted my Unicorn server and noticed that Barista correctly compiled `/javascripts/foo/bar/baz.js` now.

**Comment by hoffmanc** [comment]
Doesn't seem to be working for me.  I've attached my current Gemfile.lock here: https://gist.github.com/2200bcd487d524000996

It doesn't work even if I manually execute `bundle exec rake barista:brew`.  It indicates that CoffeScript and Javascript were compiled, but then the new subdirectory isn't there.

**Comment by hoffmanc** [comment]
This works: https://github.com/guard/guard-coffeescript
