### ISSUE TITLE
Random Node not found messages

### ISSUE THREAD

**Issue by joshcutler** [Sutto/barista#44]
I am getting "which: no nodejs in" and "which: no node in" messages all over the place with barista installed.  Thought it does manage to work because Node.js is installed.  Any idea how to suppress these?

**Comment by Sutto** [comment]
I believe this is an issue for [ExecJS](https://github.com/sstephenson/execjs/issues) as all compilation / detection is outsourced to them (Unless you're using a very old version of Barista - If so, feel free to open this issue.)
