### ISSUE TITLE
coffee-script not found error on new server

### ISSUE THREAD

**Issue by JeanMertz** [Sutto/barista#46]
I am setting up a new production server and was under the impression that I had everything set up correctly. However, when I do `rake RAILS_ENV=production barista:brew` I get:

`CoffeeScript doesn't appear to be installed on this system and you're not using an embedded compiler.`

However, `coffee -v` returns `CoffeeScript version 1.1.1`. I installed using `node.js` and `nmp`. I also tried manually installing the gem on the server using `gem install coffee-script` but even after doing that I still get the same error.

The error happens both when using capistrano with a barista command and trying to run the command through ssh. Any idea?

**Comment by Sutto** [comment]
This should be fixed on 1.2 - We now fall back to using the coffee-script detection from ExecJS so make sure you bundle update execjs after adding it. It doesn't use coffe-script via npm anymore, but it does expect that commands called either 'nodejs' or 'node' are available in your path.

Feel free to reopen if it's still broken.
