### ISSUE TITLE
therubyracer not being picked up in version 1.1

### ISSUE THREAD

**Issue by rweald** [Sutto/barista#48]
When I updated to version 1.1 all of a sudden every time I run `rake barista:brew` I always get the following error message:
`CoffeeScript doesn't appear to be installed on this system and you're not using an embedded compiler`

However I have therubyracer installed and it works on version 1.0. 
running with bundle exec rake barista:brew does not fix the problem

**Comment by Sutto** [comment]
See #46 - I believe this is the same thing. I'll close this one so we can continue the conversation there. This should be fixed shortly in 1.2
