### ISSUE TITLE
 Barista::CompilationError when javascript doesn't compile

### ISSUE THREAD

**Issue by pomartel** [Sutto/barista#5]
With latest version of Coffeescript (0.9.4) and Barista 0.5.1, I get this error when I have a syntax error in my coffeescript file :

"coffee -p --no-wrap '/Users/po/code/vendeur/app/coffeescripts/lunch.coffee'" exited with a non-zero status.

It used to tell me where the error was but now I have to manually run the coffee command to get a clue :

Error: In /Users/po/code/vendeur/app/coffeescripts/lunch.coffee, Parse error on line 13: Unexpected '='
    at Object.parseError (/usr/local/lib/coffee-script/lib/parser.js:513:11)
    ...

Is this the normal behavior?

**Comment by Sutto** [comment]
I believe this was a change to how we report errors in Barista - my suggestion is to tie into the compilation_failed hook (via Barista.on_compilation_error - see the README) - this provides the error message as the second argument to your block.

**Comment by pomartel** [comment]
I will have a look but displaying the Coffeescript error should probably be the default behavior of Barista. Without the error message, you have no idea where's the error in the code.

**Comment by stephencelis** [comment]
+1 pomartel

Default functionality should be helpful, not obscure.

**Comment by bawNg** [comment]
+1

**Comment by Sutto** [comment]
I'm doing a big overhaul of stuff for 1.0, And this has been added by default.

**Comment by Sutto** [comment]
Check out the latest gem - v0.7.0.pre2 - This automatically sets up an error warning by default.

**Comment by pomartel** [comment]
Thanks for the change Sutto! It works for me.
