### ISSUE TITLE
add minification step

### ISSUE THREAD

**Issue by vpereira** [Sutto/barista#51]
i was wondering if we can add a minify step, using uglifier gem, to the compilation process.

**Comment by glebm** [comment]
This probably should not be a responsibility of barista.
Take a look at jammit for production (http://documentcloud.github.com/jammit/)

**Comment by Sutto** [comment]
Yehp - My stance is that Barista should be responsible for the compilation process. You should be able to use barista's hook system to add support as an extra gem - and I'd be happy to link to it if you were so inclined.
