### ISSUE TITLE
Feature: joining framework files into a single output file.

### ISSUE THREAD

**Issue by mkroman** [Sutto/barista#55]
Hey.

I was looking for a feature that would join all files in a registered framework into a single javascript file, although with barista  this was simply not possible. That's why I'm here, requesting this feature.

Just in case you don't get what I mean, I've provided these examples.

Say I register a framework like this:

```
Barista::Framework.register "uploader", {
      join: true, # or :bundle.. your choice.
      root: "lib/scripts/uploader", # => app/lib/scripts/uploader/*.coffee
    output: "vendor/uploader" # => /javascripts/vendor/uploader.js
}
```

Then I want it to compile all .coffee files inside app/lib/scripts/uploader/ (:root) and all it's subdirectories, concatenate it and save it as javascripts/vendor/uploader.js.

Thanks in advance.

**Comment by Sutto** [comment]
The potential issue with this feature is that it means barista needs some way to know the order of concatenation for files within a framework or the user needs to declare it in some manner - Given that is the case, my typical stance is that barista should be ignorant of these things (e.g. it should be usable in combination with other tools such as Jammit which do it well) versus implementing some form of asset packaging itself.

I'd potentially be happy to accept patches for it (given solid reasoning, as I can see it being useful) but I personally feel it's something better left up to either plugins for Barista (using hooks) or barista + {jammit,sprockets,some-other-package-manasger}.

**Comment by mkroman** [comment]
Yeah, you are absolutely right. I didn't know of Jammit, so I've been investigating it and I've successfully set up what I wanted to do, and I even got automatic compression and embedded images and fonts!

So thank you very much.
Jammit is indeed the way to go, it suits more needs than the Framework.register hack ever would.
